### ISSUE TITLE
Add markdown in notebook files as code comments

### ISSUE THREAD

**Issue by EdmundGoodman** [EdmundGoodman/Jupyter_Pylinter#3]
It would be beneficial if the markdown in the notebook files were also included in the output code (or at least a flag to allow doing so), as this would allow a corollary use case of generating python files including the entire content of the notebook

**Comment by byw2** [comment]
Can I pleased be assigned to this? thanks!

**Comment by EdmundGoodman** [comment]
Closed due to archiving. Similar functionality can be achieved via [jupytext](https://github.com/mwouts/jupytext)
